"""Task data model for the Todo CLI application."""

from dataclasses import dataclass


@dataclass
class Task:
    """Represents a single todo item.

    Attributes:
        id: Unique numeric identifier (immutable, auto-generated by TaskManager)
        title: Task title (1-200 characters, required)
        description: Detailed notes about the task (0-500 characters, optional)
        completed: Completion status (False=pending, True=completed)
    """

    id: int
    title: str
    description: str = ""
    completed: bool = False
